package com.tripplanner.Enum;

public class Constants {
	public enum teacher_storage{
		APP_TEACHER_SETTINGS,
		APP_TEACHER_LOGIN_USERNAME,
		APP_TEACHER_LOGIN_PASSWORD,
		TEACHER_REMEMBER_ME,
		TEACHER_NAME_PREFIX,
		TEACHER_FIRST_NAME,
		TEACHER_MIDDLE_NAME,
		TEACHER_LAST_NAME,
		TEACHER_PHONE,
		TEACHER_USER_ID,
		TEACHER_STATE,
		TEACHER_CITY,
		TEACHER_DISTRICT,
		TEACHER_SCHOOL,
		TEACHER_OTHER_SCHOOL;				
	}
	public enum parent_storage{
		APP_PARENT_SETTINGS,
		APP_PARENT_LOGIN_USERNAME,
		APP_PARENT_LOGIN_PASSWORD,
		PARENT_REMEMBER_ME,		
		PARENT_FIRST_NAME,		
		PARENT_LAST_NAME,
		PARENT_PHONE,
		PARENT_USER_ID;				
	}
}
